var wldata = {"lang": "en", "data": {"adjectives": [["abusive"], ["alert"],
["alive"], ["ancient"], ["angry"], ["anxious"], ["aquatic"], ["average"],
["awful"], ["baggy"], ["bald"], ["bashful"], ["bizarre"], ["blind"], ["bossy"],
["brave"], ["brawny"], ["bright"], ["bubbly"], ["busy"], ["careful"],
["casual"], ["cheap"], ["cheery"], ["chilly"], ["chunky"], ["classy"],
["clean"], ["clever"], ["clumsy"], ["coarse"], ["cold"], ["compact"],
["cool"], ["corrupt"], ["costly"], ["crazy"], ["creamy"], ["creepy"],
["crisp"], ["crooked"], ["crude"], ["cruel"], ["crusty"], ["cuddly"],
["curious"], ["curly"], ["dainty"], ["dark"], ["deadly"], ["dizzy"], ["drab"],
["drowsy"], ["dull"], ["dumb"], ["dynamic"], ["eager"], ["early"], ["earthy"],
["edgy"], ["elegant"], ["elite"], ["empty"], ["extreme"], ["fair"], ["famous"],
["fancy"], ["festive"], ["fiery"], ["fine"], ["finicky"], ["firm"], ["fishy"],
["flaky"], ["flimsy"], ["fluffy"], ["foamy"], ["foolish"], ["fragile"],
["frail"], ["frantic"], ["free"], ["fresh"], ["frilly"], ["frosty"],
["fuzzy"], ["gentle"], ["ghastly"], ["giddy"], ["gloomy"], ["glossy"],
["good"], ["goofy"], ["grassy"], ["greasy"], ["green"], ["grey"], ["grim"],
["gritty"], ["groovy"], ["grouchy"], ["grubby"], ["grumpy"], ["guilty"],
["hapless"], ["happy"], ["harsh"], ["hasty"], ["hazy"], ["heavy"],
["helpful"], ["hollow"], ["honest"], ["huge"], ["hungry"], ["husky"],
["icky"], ["idiotic"], ["itchy"], ["jagged"], ["jealous"], ["jolly"],
["joyous"], ["large"], ["leafy"], ["little"], ["lofty"], ["lousy"],
["lovely"], ["lowly"], ["lumpy"], ["macho"], ["magical"], ["massive"],
["mean"], ["merry"], ["messy"], ["mighty"], ["modern"], ["moldy"],
["muddy"], ["narrow"], ["nervous"], ["nice"], ["nifty"], ["oafish"],
["obscure"], ["offbeat"], ["painful"], ["petty"], ["pink"], ["plain"],
["polite"], ["posh"], ["prickly"], ["prompt"], ["proud"], ["prudent"],
["puffy"], ["puny"], ["pure"], ["purple"], ["quaint"], ["quiet"], ["rampant"],
["raspy"], ["ratty"], ["real"], ["rich"], ["ripe"], ["roasted"], ["rocky"],
["roomy"], ["rosy"], ["rough"], ["royal"], ["rustic"], ["safe"], ["sandy"],
["sassy"], ["savory"], ["scary"], ["scruffy"], ["selfish"], ["shabby"],
["shady"], ["shallow"], ["sheer"], ["shiny"], ["silent"], ["silly"],
["simple"], ["sincere"], ["sketchy"], ["skinny"], ["sleazy"], ["sleepy"],
["slimy"], ["sloppy"], ["slow"], ["small"], ["smart"], ["smelly"], ["smooth"],
["smug"], ["sneaky"], ["snowy"], ["soft"], ["soggy"], ["somber"], ["spicy"],
["spooky"], ["square"], ["squeaky"], ["steady"], ["stocky"], ["stout"],
["strange"], ["strict"], ["strong"], ["stuffy"], ["stupid"], ["sturdy"],
["sulky"], ["sweet"], ["swift"], ["tall"], ["thick"], ["thirsty"], ["tidy"],
["trashy"], ["trendy"], ["tricky"], ["typical"], ["ugly"], ["upbeat"],
["upset"], ["uptight"], ["urgent"], ["used"], ["vague"], ["vast"], ["wacky"],
["wealthy"], ["weary"], ["wild"], ["wise"], ["witty"], ["woolly"], ["woozy"],
["worldly"], ["worthy"], ["wrong"], ["yellow"], ["zany"], ["zippy"]], "verbs":
[["absorbing", "absorb", "absorbed", "absorbs"], ["accessing", "access",
"accessed", "accesses"], ["accusing", "accuse", "accused", "accuses"],
["adjusting", "adjust", "adjusted", "adjusts"], ["admiring", "admire",
"admired", "admires"], ["affording", "afford", "afforded", "affords"],
["alleging", "allege", "alleged", "alleges"], ["allowing", "allow", "allowed",
"allows"], ["altering", "alter", "altered", "alters"], ["annoying", "annoy",
"annoyed", "annoys"], ["answering", "answer", "answered", "answers"],
["appearing", "appear", "appeared", "appears"], ["assisting", "assist",
"assisted", "assists"], ["attaching", "attach", "attached", "attaches"],
["avoiding", "avoid", "avoided", "avoids"], ["awaiting", "await", "awaited",
"awaits"], ["battling", "battle", "battled", "battles"], ["behaving", "behave",
"behaved", "behaves"], ["belonging", "belong", "belonged", "belongs"],
["bleaching", "bleach", "bleached", "bleaches"], ["blocking", "block",
"blocked", "blocks"], ["boiling", "boil", "boiled", "boils"], ["boosting",
"boost", "boosted", "boosts"], ["borrowing", "borrow", "borrowed", "borrows"],
["bouncing", "bounce", "bounced", "bounces"], ["breaking", "break", "broke",
"breaks", "broken"], ["bringing", "bring", "brought", "brings"], ["bruising",
"bruise", "bruised", "bruises"], ["building", "build", "built", "builds"],
["bumping", "bump", "bumped", "bumps"], ["bursting", "burst", "bursts"],
["carrying", "carry", "carried", "carries"], ["carving", "carve", "carved",
"carves", "carven"], ["charging", "charge", "charged", "charges"], ["chasing",
"chase", "chased", "chases"], ["chatting", "chat", "chatted", "chats"],
["checking", "check", "checked", "checks"], ["chopping", "chop", "chopped",
"chops"], ["climbing", "climb", "climbed", "climbs"], ["clipping", "clip",
"clipped", "clips"], ["clutching", "clutch", "clutched", "clutches"],
["conferring", "confer", "conferred", "confers"], ["copying", "copy",
"copied", "copies"], ["costing", "cost", "costs"], ["covering", "cover",
"covered", "covers"], ["cracking", "crack", "cracked", "cracks"], ["creating",
"create", "created", "creates"], ["crossing", "cross", "crossed", "crosses"],
["crushing", "crush", "crushed", "crushes"], ["damaging", "damage", "damaged",
"damages"], ["dancing", "dance", "danced", "dances"], ["debating", "debate",
"debated", "debates"], ["decaying", "decay", "decayed", "decays"], ["deeming",
"deem", "deemed", "deems"], ["defending", "defend", "defended", "defends"],
["defining", "define", "defined", "defines"], ["demanding", "demand",
"demanded", "demands"], ["denying", "deny", "denied", "denies"],
["departing", "depart", "departed", "departs"], ["designing", "design",
"designed", "designs"], ["detecting", "detect", "detected", "detects"],
["disarming", "disarm", "disarmed", "disarms"], ["diverting", "divert",
"diverted", "diverts"], ["doubling", "double", "doubled", "doubles"],
["draining", "drain", "drained", "drains"], ["dreaming", "dream", "dreamt",
"dreams"], ["dropping", "drop", "dropped", "drops"], ["drowning", "drown",
"drowned", "drowns"], ["echoing", "echo", "echoed", "echoes"], ["emerging",
"emerge", "emerged", "emerges"], ["engaging", "engage", "engaged", "engages"],
["enjoying", "enjoy", "enjoyed", "enjoys"], ["entering", "enter", "entered",
"enters"], ["escaping", "escape", "escaped", "escapes"], ["evolving", "evolve",
"evolved", "evolves"], ["exceeding", "exceed", "exceeded", "exceeds"],
["exciting", "excite", "excited", "excites"], ["exerting", "exert", "exerted",
"exerts"], ["expanding", "expand", "expanded", "expands"], ["exposing",
"expose", "exposed", "exposes"], ["fastening", "fasten", "fastened",
"fastens"], ["feeing", "feed", "fees"], ["fetching", "fetch", "fetched",
"fetches"], ["finishing", "finish", "finished", "finishes"], ["flinging",
"fling", "flung", "flings"], ["floating", "float", "floated", "floats"],
["flowering", "flower", "flowered", "flowers"], ["focussing", "focus",
"focussed", "focuses"], ["forbidding", "forbid", "forbade", "forbids",
"forbidden"], ["forcing", "force", "forced", "forces"], ["forgetting",
"forget", "forgot", "forgets", "forgotten"], ["freezing", "freeze", "froze",
"freezes", "frozen"], ["fulfilling", "fulfil", "fulfilled", "fufils"],
["gaining", "gain", "gained", "gains"], ["glancing", "glance", "glanced",
"glances"], ["governing", "govern", "governed", "governs"], ["granting",
"grant", "granted", "grants"], ["grasping", "grasp", "grasped", "grasps"],
["groaning", "groan", "groaned", "groans"], ["guarding", "guard", "guarded",
"guards"], ["guiding", "guide", "guided", "guides"], ["hammering", "hammer",
"hammered", "hammers"], ["harming", "harm", "harmed", "harms"], ["haunting",
"haunt", "haunted", "haunts"], ["helping", "help", "helped", "helps"],
["hiding", "hide", "hid", "hides", "hidden"], ["ignoring", "ignore", "ignored",
"ignores"], ["importing", "import", "imported", "imports"], ["informing",
"inform", "informed", "informs"], ["injecting", "inject", "injected",
"injects"], ["injuring", "injure", "injured", "injures"], ["inserting",
"insert", "inserted", "inserts"], ["insisting", "insist", "insisted",
"insists"], ["inventing", "invent", "invented", "invents"], ["joining",
"join", "joined", "joins"], ["joking", "joke", "joked", "jokes"], ["judging",
"judge", "judged", "judges"], ["juggling", "juggle", "juggled", "juggles"],
["keeping", "keep", "kept", "keeps"], ["kicking", "kick", "kicked", "kicks"],
["knitting", "knit", "knitted", "knits"], ["knocking", "knock", "knocked",
"knocks"], ["labelling", "label", "labelled", "labels"], ["laughing", "laugh",
"laughed", "laughs"], ["launching", "launch", "launched", "launches"],
["locating", "locate", "located", "locates"], ["loving", "love", "loved",
"loves"], ["managing", "manage", "managed", "manages"], ["matching", "match",
"matched", "matches"], ["minding", "mind", "minded", "minds"], ["murdering",
"murder", "murdered", "murders"], ["murmuring", "murmur", "murmured",
"murmurs"], ["muttering", "mutter", "muttered", "mutters"], ["naming",
"name", "named", "names"], ["noticing", "notice", "noticed", "notices"],
["obeying", "obey", "obeyed", "obeys"], ["obtaining", "obtain", "obtained",
"obtains"], ["occupying", "occupy", "occupied", "occupies"], ["opening",
"open", "opened", "opens"], ["ordering", "order", "ordered", "orders"],
["painting", "paint", "painted", "paints"], ["pasting", "paste", "pasted",
"pastes"], ["pausing", "pause", "paused", "pauses"], ["pecking", "peck",
"pecked", "pecks"], ["peeling", "peel", "peeled", "peels"], ["permitting",
"permit", "permitted", "permits"], ["pleading", "plead", "pled", "pleads"],
["pluging", "plug", "pluged", "plugs"], ["praising", "praise", "praised",
"praises"], ["preaching", "preach", "preached", "preaches"], ["pressing",
"press", "pressed", "presses"], ["proving", "prove", "proved", "proves",
"proven"], ["punching", "punch", "punched", "punches"], ["punishing", "punish",
"punished", "punishes"], ["pursuing", "pursue", "pursued", "pursues"],
["quoting", "quote", "quoth", "quotes", "quoted"], ["reacting", "react",
"reacted", "reacts"], ["recalling", "recall", "recalled", "recalls"],
["reckoning", "reckon", "reckoned", "reckons"], ["recording", "record",
"recorded", "records"], ["reducing", "reduce", "reduced", "reduces"],
["refusing", "refuse", "refused", "refuses"], ["regaining", "regain",
"regained", "regains"], ["regretting", "regret", "regretted", "regrets"],
["reigning", "reign", "reigned", "reigns"], ["rejecting", "reject", "rejected",
"rejects"], ["relaxing", "relax", "relaxed", "relaxes"], ["removing",
"remove", "removed", "removes"], ["renting", "rent", "rented", "rents"],
["repairing", "repair", "repaired", "repairs"], ["repeating", "repeat",
"repeated", "repeats"], ["reporting", "report", "reported", "reports"],
["rescuing", "rescue", "rescued", "rescues"], ["resisting", "resist",
"resisted", "resists"], ["retiring", "retire", "retired", "retires"],
["returning", "return", "returned", "returns"], ["revealing", "reveal",
"revealed", "reveals"], ["reviewing", "review", "reviewed", "reviews"],
["rewarding", "reward", "rewarded", "rewards"], ["rhyming", "rhyme",
"rhymed", "rhymes"], ["rinsing", "rinse", "rinsed", "rinses"], ["risking",
"risk", "risked", "risks"], ["rolling", "roll", "rolled", "rolls"],
["ruining", "ruin", "ruined", "ruins"], ["ruling", "rule", "ruled",
"rules"], ["scorching", "scorch", "scorched", "scorches"], ["scraping",
"scrape", "scraped", "scrapes"], ["scrubbing", "scrub", "scrubbed", "scrubs"],
["searching", "search", "searched", "searches"], ["seizing", "seize", "seized",
"seizes"], ["selecting", "select", "selected", "selects"], ["sensing", "sense",
"sensed", "senses"], ["shaping", "shape", "shaped", "shapes"], ["shivering",
"shiver", "shivered", "shivers"], ["shocking", "shock", "shocked", "shocks"],
["shrugging", "shrug", "shrugged", "shrugs"], ["shutting", "shut", "shuts"],
["signalling", "signal", "signalled", "signals"], ["sliding", "slide", "slid",
"slides", "slidden"], ["smashing", "smash", "smashed", "smashes"], ["smiling",
"smile", "smiled", "smiles"], ["smoking", "smoke", "smoked", "smokes"],
["sniffing", "sniff", "sniffed", "sniffs"], ["solving", "solve", "solved",
"solves"], ["soothing", "soothe", "soothed", "soothes"], ["sparking", "spark",
"sparked", "sparks"], ["spelling", "spell", "spelt", "spells"], ["spinning",
"spin", "spun", "spins"], ["splitting", "split", "splits"], ["spoiling",
"spoil", "spoilt", "spoils"], ["spotting", "spot", "spotted", "spots",
"spotcheck"], ["spraying", "spray", "sprayed", "sprays"], ["spreading",
"spread", "spreads"], ["springing", "spring", "sprung", "springs"],
["sprouting", "sprout", "sprouted", "sprouts"], ["squashing", "squash",
"squashed", "squashes"], ["squealing", "squeal", "squealed", "squeals"],
["stamping", "stamp", "stamped", "stamps"], ["stirring", "stir", "stirred",
"stirs"], ["stopping", "stop", "stopped", "stops"], ["straining", "strain",
"strained", "strains"], ["stressing", "stress", "stressed", "stresses"],
["stroking", "stroke", "stroked", "strokes"], ["suffering", "suffer",
"suffered", "suffers"], ["suiting", "suit", "suited", "suits"], ["summoning",
"summon", "summoned", "summons"], ["swinging", "swing", "swung", "swings"],
["teaching", "teach", "taught", "teaches"], ["teasing", "tease", "teased",
"teases"], ["tempting", "tempt", "tempted", "tempts"], ["tending", "tend",
"tended", "tends"], ["thawing", "thaw", "thawed", "thaws"], ["throwing",
"throw", "threw", "throws", "thrown"], ["thrusting", "thrust", "thrusts"],
["tickling", "tickle", "tickled", "tickles"], ["tossing", "toss", "tossed",
"tosses"], ["touching", "touch", "touched", "touches"], ["travelling",
"travel", "travelled", "travels"], ["trotting", "trot", "trotted", "trots"],
["tumbling", "tumble", "tumbled", "tumbles"], ["twisting", "twist", "twisted",
"twists"], ["unpacking", "unpack", "unpacked", "unpacks"], ["updating",
"update", "updated", "updates"], ["viewing", "view", "viewed", "views"],
["visiting", "visit", "visited", "visits"], ["walking", "walk", "walked",
"walks"], ["wanting", "want", "wanted", "wants"], ["warning", "warn",
"warned", "warns"], ["waving", "wave", "waved", "waves"], ["weakening",
"weaken", "weakened", "weakens"], ["weighing", "weigh", "weighed", "weighs"],
["widening", "widen", "widened", "widens"], ["working", "work", "worked",
"works"], ["wrapping", "wrap", "wrapped", "wraps"], ["wrecking", "wreck",
"wrecked", "wrecks"], ["writing", "write", "wrote", "writes", "written"]],
"nouns": [["acid"], ["agent"], ["alarm"], ["album"], ["ally"], ["animal"],
["area"], ["army"], ["artist"], ["author"], ["avenue"], ["bank"], ["basket"],
["beam"], ["bell"], ["bench"], ["bike"], ["bird"], ["blade"], ["board"],
["boat"], ["brand"], ["bridge"], ["bronze"], ["button"], ["cable"], ["cake"],
["camera"], ["canal"], ["carbon"], ["card"], ["cash"], ["castle"], ["chair"],
["cheese"], ["chief"], ["cinema"], ["circle"], ["city"], ["clay"], ["clerk"],
["client"], ["cliff"], ["clinic"], ["cloth"], ["cloud"], ["club"], ["coffee"],
["colony"], ["column"], ["copper"], ["corner"], ["cotton"], ["court"],
["craft"], ["crew"], ["critic"], ["crowd"], ["data"], ["deputy"], ["desk"],
["device"], ["diary"], ["dinner"], ["doctor"], ["dollar"], ["door"], ["duke"],
["dust"], ["eagle"], ["editor"], ["enemy"], ["energy"], ["engine"], ["essay"],
["estate"], ["event"], ["fabric"], ["fang"], ["farmer"], ["fence"], ["field"],
["filter"], ["flag"], ["flame"], ["fleet"], ["floor"], ["fluid"], ["forest"],
["forum"], ["friend"], ["frog"], ["front"], ["fruit"], ["fuel"], ["garage"],
["garden"], ["ghost"], ["gift"], ["glass"], ["goal"], ["golf"], ["ground"],
["growth"], ["guest"], ["guitar"], ["heart"], ["hero"], ["hill"], ["horse"],
["hotel"], ["hour"], ["image"], ["inch"], ["iron"], ["island"], ["item"],
["jacket"], ["juice"], ["jury"], ["killer"], ["kitten"], ["knee"], ["knife"],
["lawyer"], ["leader"], ["lesson"], ["letter"], ["lion"], ["lizard"], ["loan"],
["lord"], ["margin"], ["mayor"], ["menu"], ["metal"], ["miner"], ["mirror"],
["module"], ["money"], ["moon"], ["motor"], ["mouse"], ["movie"], ["muscle"],
["museum"], ["music"], ["navy"], ["nerve"], ["nest"], ["night"], ["novel"],
["number"], ["ocean"], ["office"], ["opera"], ["option"], ["orange"],
["organ"], ["owner"], ["oxygen"], ["page"], ["palace"], ["palm"], ["panel"],
["paper"], ["party"], ["path"], ["photo"], ["piano"], ["pile"], ["pilot"],
["pitch"], ["pizza"], ["planet"], ["plate"], ["pocket"], ["poem"], ["policy"],
["pond"], ["port"], ["potato"], ["prince"], ["prize"], ["profit"],
["public"], ["pupil"], ["rabbit"], ["rebel"], ["recipe"], ["remedy"],
["riot"], ["rival"], ["river"], ["road"], ["robin"], ["roof"], ["route"],
["safety"], ["salary"], ["salt"], ["scale"], ["scene"], ["school"], ["screen"],
["seat"], ["seller"], ["server"], ["shadow"], ["shoe"], ["silver"], ["site"],
["slope"], ["snail"], ["song"], ["space"], ["sphere"], ["spider"], ["squad"],
["staff"], ["stance"], ["steam"], ["steel"], ["stone"], ["storm"], ["street"],
["studio"], ["style"], ["survey"], ["sword"], ["symbol"], ["system"],
["taxi"], ["temple"], ["tenant"], ["text"], ["ticket"], ["timber"], ["tissue"],
["title"], ["tomato"], ["tower"], ["tray"], ["treaty"], ["tutor"], ["union"],
["valley"], ["vendor"], ["video"], ["virus"], ["voter"], ["wheel"], ["window"],
["world"], ["youth"], ["zebra"]]}, "lists": ["adjectives", "nouns", "verbs"]};
// for node
if (typeof module === 'object' && 'exports' in module) module.exports = wldata;
